#************************************************
# makefile for 
#------------------------------------------------
# blueantelope@gmail.com
# blueantelope 2015-04-21
#************************************************

ROOT_DIR =.
SRC =$(ROOT_DIR)/src
PY =python
PY_ARGS =-m py_compile

.PHONY : clean


